### ISSUE TITLE
Ubuntu 14.04 (3.16.0-50-generic)

### ISSUE THREAD

**Issue by ahojjati** [citostyle/docker-record#1]
Running ./docker-record "container name" complains:
from docker import client 
ImportError: No module name docker 

*Fix run  "pip install docker-py"

**Comment by allonhadaya** [comment]
`pip install -r requirements.txt` will also do the trick. :wink:

**Comment by ahojjati** [comment]
right on! 

p.s might need to run "pip install docopt" still. running "requirements.txt" didn't cover this.
